defmodule Saturno.Sensazonal do
  import SaturnoWeb.Gettext

  def list_foods(first) when is_integer(first) do
    foods()
    |> Enum.take(first)
  end

  def list_foods(_) do
    foods()
  end

  def foods do
    [
      %{  
        id: 1,
        name: gettext("Pineapple"),
        group: gettext("Fruit"),
        months: [1, 3, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Star Fruit"),
        group: gettext("Fruit"),
        months: [1, 2, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/STAR_FRUIT.imageset/STAR_FRUIT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Green Coconut"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GREEN_COCONUT.imageset/GREEN_COCONUT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fig"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/FIG.imageset/FIG%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Raspberry"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/RASPBERRY.imageset/RASPBERRY%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Custard Apple"),
        group: gettext("Fruit"),
        months: [1, 2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CUSTARD_APPLE.imageset/CUSTARD_APPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Orange Pear"),
        group: gettext("Fruit"),
        months: [1, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ORANGE_PEAR.imageset/ORANGE_PEAR%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Orange-lime"),
        group: gettext("Fruit"),
        months: [6, 7, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ORANGE_LIME.imageset/ORANGE_LIME%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Papaya"),
        group: gettext("Fruit"),
        months: [1, 3, 4, 8, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PAPAYA.imageset/PAPAYA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Passion Fruit"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PASSION_FRUIT.imageset/PASSION_FRUIT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Watermelon"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/WATERMELON.imageset/WATERMELON%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Nectarine"),
        group: gettext("Fruit"),
        months: [1, 3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/NECTARINE.imageset/NECTARINE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Grape"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 4, 5, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GRAPE.imageset/GRAPE%403x.jpeg",
      },
      %{  
        id: 1,
        name: gettext("Lettuce"),
        group: gettext("Vegetable"),
        months: [1, 3, 4],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/LETTUCE.imageset/LETTUCE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chive"),
        group: gettext("Vegetable"),
        months: [1, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CHIVE.imageset/CHIVE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cabbage"),
        group: gettext("Vegetable"),
        months: [1, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CABBAGE.imageset/CABBAGE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Parsley"),
        group: gettext("Vegetable"),
        months: [1, 3, 7, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PARSLEY.imageset/PARSLEY%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pumpkin"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PUMPKIN.imageset/PUMPKIN%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Zucchini"),
        group: gettext("Veggie"),
        months: [1, 3, 5, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ZUCCHINI.imageset/ZUCCHINI%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Beet"),
        group: gettext("Veggie"),
        months: [1, 3, 4, 5, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BEET.imageset/BEET%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cucumber"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 7, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CUCUMBER.imageset/CUCUMBER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pepper"),
        group: gettext("Veggie"),
        months: [1, 2, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PEPPER.imageset/PEPPER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Okra"),
        group: gettext("Veggie"),
        months: [1, 2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/OKRA.imageset/OKRA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tomato"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/TOMATO.imageset/TOMATO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Avocado"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/AVOCADO.imageset/AVOCADO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Plum"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PLUM.imageset/PLUM%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Guava"),
        group: gettext("Fruit"),
        months: [2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GUAVA.imageset/GUAVA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Jaca"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/JACA.imageset/JACA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Apple"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/APPLE.imageset/APPLE%403x.jpeg",
      },
      %{  
        id: 1,
        name: gettext("Pear"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PEAR.imageset/PEAR%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Peach"),
        group: gettext("Fruit"),
        months: [2, 3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PEACH.imageset/PEACH%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Seriguela"),
        group: gettext("Fruit"),
        months: [2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/SERIGUELA.imageset/SERIGUELA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Escarole"),
        group: gettext("Vegetable"),
        months: [2, 3, 4, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ESCAROLE.imageset/ESCAROLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mint"),
        group: gettext("Vegetable"),
        months: [2, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MINT.imageset/MINT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Ginger"),
        group: gettext("Veggie"),
        months: [2, 3, 4, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GINGER.imageset/GINGER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Green Corn"),
        group: gettext("Veggie"),
        months: [2, 3, 6, 7],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GREEN_CORN.imageset/GREEN_CORN%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Banana Apple"),
        group: gettext("Fruit"),
        months: [3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BANANA_APPLE.imageset/BANANA_APPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Banana Nanica"),
        group: gettext("Fruit"),
        months: [3, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BANANA_NANICA.imageset/BANANA_NANICA%403x.jpeg",
      },
      %{  
        id: 1,
        name: gettext("Lemon"),
        group: gettext("Fruit"),
        months: [3, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/LEMON.imageset/LEMON%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mangosteen"),
        group: gettext("Fruit"),
        months: [3, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MANGOSTEEN.imageset/MANGOSTEEN%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tangerine"),
        group: gettext("Fruit"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/TANGERINE.imageset/TANGERINE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chard"),
        group: gettext("Vegetable"),
        months: [3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CHARD.imageset/CHARD%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Leek"),
        group: gettext("Vegetable"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/LEEK.imageset/LEEK%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Coriander"),
        group: gettext("Vegetable"),
        months: [3, 7, 8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CORIANDER.imageset/CORIANDER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Endive"),
        group: gettext("Vegetable"),
        months: [3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ENDIVE.imageset/ENDIVE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Arugula"),
        group: gettext("Vegetable"),
        months: [3, 8, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ARUGULA.imageset/ARUGULA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Eggplant"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/EGGPLANT.imageset/EGGPLANT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cará"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 7, 8, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CARA.imageset/CARA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chuchu"),
        group: gettext("Veggie"),
        months: [3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CHUCHU.imageset/CHUCHU%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Yam"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/YAM.imageset/YAM%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Scarlet Eggplant"),
        group: gettext("Veggie"),
        months: [3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/SCARLET_EGGPLANT.imageset/SCARLET_EGGPLANT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Turnip"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 7, 8, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/TURNIP.imageset/TURNIP%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Khaki"),
        group: gettext("Fruit"),
        months: [4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/KHAKI.imageset/KHAKI%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cider"),
        group: gettext("Fruit"),
        months: [4],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CIDER.imageset/CIDER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Kiwi"),
        group: gettext("Fruit"),
        months: [4, 5, 6, 7, 8, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/KIWI.imageset/KIWI%403x.jpeg",
      },
      %{  
        id: 1,
        name: gettext("Will Reach"),
        group: gettext("Vegetable"),
        months: [4, 5, 6, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/WILL_REACH.imageset/WILL_REACH%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Catalan"),
        group: gettext("Vegetable"),
        months: [4, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CATALAN.imageset/CATALAN%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fennel"),
        group: gettext("Vegetable"),
        months: [5, 6, 7, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/FENNEL.imageset/FENNEL%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Bay Laurel"),
        group: gettext("Vegetable"),
        months: [5, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BAY_LAUREL.imageset/BAY_LAUREL%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Sweet Potato"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/SWEET_POTATO.imageset/SWEET_POTATO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Carrot"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CARROT.imageset/CARROT%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Manioc"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MANIOC.imageset/MANIOC%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Little Manioc"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MANIOC.imageset/MANIOC%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Radish"),
        group: gettext("Veggie"),
        months: [5, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/RADISH.imageset/RADISH%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Quince"),
        group: gettext("Fruit"),
        months: [6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/QUINCE.imageset/QUINCE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cress"),
        group: gettext("Vegetable"),
        months: [6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/WATERCRESS.imageset/WATERCRESS%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Broccoli"),
        group: gettext("Vegetable"),
        months: [6, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BROCCOLI.imageset/BROCCOLI%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pea"),
        group: gettext("Veggie"),
        months: [6, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PEA.imageset/PEA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Palm Heart"),
        group: gettext("Veggie"),
        months: [6, 7],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PALM_HEART.imageset/PALM_HEART%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chicory"),
        group: gettext("Vegetable"),
        months: [7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CHICORY.imageset/CHICORY%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Spinach"),
        group: gettext("Vegetable"),
        months: [7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/SPINACH.imageset/SPINACH%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mustard"),
        group: gettext("Vegetable"),
        months: [7, 8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MUSTARD.imageset/MUSTARD%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Celery"),
        group: gettext("Vegetable"),
        months: [7, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CELERY.imageset/CELERY%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mushroom"),
        group: gettext("Veggie"),
        months: [7, 9, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MUSHROOM.imageset/MUSHROOM%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cashew"),
        group: gettext("Fruit"),
        months: [8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lime"),
        group: gettext("Fruit"),
        months: [8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/LIME.imageset/LIME%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Strawberry"),
        group: gettext("Fruit"),
        months: [8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/STRAWBERRY.imageset/STRAWBERRY%403x.jpeg",
      },
      %{  
        id: 1,
        name: gettext("Cauliflower"),
        group: gettext("Vegetable"),
        months: [8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CAULIFLOWER.imageset/CAULIFLOWER%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fava"),
        group: gettext("Veggie"),
        months: [8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/BLANK.imageset/BLANK%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Jaboticaba"),
        group: gettext("Fruit"),
        months: [9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/JABOTICABA.imageset/JABOTICABA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Medlar"),
        group: gettext("Fruit"),
        months: [9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MEDLAR.imageset/MEDLAR%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tamarind"),
        group: gettext("Fruit"),
        months: [9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/TAMARIND.imageset/TAMARIND%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Oregano"),
        group: gettext("Vegetable"),
        months: [9, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/OREGANO.imageset/OREGANO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Acerola"),
        group: gettext("Fruit"),
        months: [10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ACEROLA.imageset/ACEROLA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Silver Banana"),
        group: gettext("Fruit"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/SILVER_BANANA.imageset/SILVER_BANANA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mango"),
        group: gettext("Fruit"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MANGO.imageset/MANGO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Grape Leaf"),
        group: gettext("Vegetable"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GRAPE_LEAF.imageset/GRAPE_LEAF%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Artichoke"),
        group: gettext("Veggie"),
        months: [10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ARTICHOKE.imageset/ARTICHOKE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Asparagus"),
        group: gettext("Veggie"),
        months: [10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/ASPARAGUS.imageset/ASPARAGUS%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Khaki Tomato"),
        group: gettext("Fruit"),
        months: [10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/KHAKI_TOMATO.imageset/KHAKI_TOMATO%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Melon"),
        group: gettext("Fruit"),
        months: [11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MELON.imageset/MELON%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Maxixe"),
        group: gettext("Veggie"),
        months: [11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/MAXIXE.imageset/MAXIXE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cherry"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/CHERRY.imageset/CHERRY%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Damascus"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/DAMASCUS.imageset/DAMASCUS%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Graviola"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/GRAVIOLA.imageset/GRAVIOLA%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lychee"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/LYCHEE.imageset/LYCHEE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pomegranate"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/POMEGRANATE.imageset/POMEGRANATE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pod Noodles"),
        group: gettext("Veggie"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/POD_NOODLES.imageset/POD_NOODLES%403x.jpeg",
      }
    ]
  end
end
