defmodule Saturno.Sensazonal do
  import SaturnoWeb.Gettext

  def list_foods(first) when is_integer(first) do
    foods()
    |> Enum.take(first)
  end

  def list_foods(_) do
    foods()
  end

  def foods do
    [
      %{  
        id: 1,
        name: gettext("Pineapple"),
        group: gettext("Fruit"),
        months: [1, 3, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Star Fruit"),
        group: gettext("Fruit"),
        months: [1, 2, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Green Coconut"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fig"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Raspberry"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Custard Apple"),
        group: gettext("Fruit"),
        months: [1, 2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Orange Pear"),
        group: gettext("Fruit"),
        months: [1, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Orange-lime"),
        group: gettext("Fruit"),
        months: [6, 7, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Papaya"),
        group: gettext("Fruit"),
        months: [1, 3, 4, 8, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Passion Fruit"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Watermelon"),
        group: gettext("Fruit"),
        months: [1, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Nectarine"),
        group: gettext("Fruit"),
        months: [1, 3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Grape"),
        group: gettext("Fruit"),
        months: [1, 2, 3, 4, 5, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lettuce"),
        group: gettext("Vegetable"),
        months: [1, 3, 4],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chive"),
        group: gettext("Vegetable"),
        months: [1, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cabbage"),
        group: gettext("Vegetable"),
        months: [1, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Parsley"),
        group: gettext("Vegetable"),
        months: [1, 3, 7, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pumpkin"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Zucchini"),
        group: gettext("Veggie"),
        months: [1, 3, 5, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Beet"),
        group: gettext("Veggie"),
        months: [1, 3, 4, 5, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cucumber"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 7, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pepper"),
        group: gettext("Veggie"),
        months: [1, 2, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Okra"),
        group: gettext("Veggie"),
        months: [1, 2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tomato"),
        group: gettext("Veggie"),
        months: [1, 2, 3, 4, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Avocado"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Plum"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Guava"),
        group: gettext("Fruit"),
        months: [2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Jaca"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Apple"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pear"),
        group: gettext("Fruit"),
        months: [2, 3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Peach"),
        group: gettext("Fruit"),
        months: [2, 3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Seriguela"),
        group: gettext("Fruit"),
        months: [2, 3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Escarole"),
        group: gettext("Vegetable"),
        months: [2, 3, 4, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mint"),
        group: gettext("Vegetable"),
        months: [2, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Ginger"),
        group: gettext("Veggie"),
        months: [2, 3, 4, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Green Corn"),
        group: gettext("Veggie"),
        months: [2, 3, 6, 7],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Banana Apple"),
        group: gettext("Fruit"),
        months: [3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Banana Nanica"),
        group: gettext("Fruit"),
        months: [3, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lemon"),
        group: gettext("Fruit"),
        months: [3, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mangosteen"),
        group: gettext("Fruit"),
        months: [3, 6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tangerine"),
        group: gettext("Fruit"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chard"),
        group: gettext("Vegetable"),
        months: [3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Leek"),
        group: gettext("Vegetable"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Coriander"),
        group: gettext("Vegetable"),
        months: [3, 7, 8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Endive"),
        group: gettext("Vegetable"),
        months: [3, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Arugula"),
        group: gettext("Vegetable"),
        months: [3, 8, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Eggplant"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cará"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 7, 8, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chuchu"),
        group: gettext("Veggie"),
        months: [3, 4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Yam"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Scarlet Eggplant"),
        group: gettext("Veggie"),
        months: [3],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Turnip"),
        group: gettext("Veggie"),
        months: [3, 4, 5, 7, 8, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Khaki"),
        group: gettext("Fruit"),
        months: [4, 5],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cider"),
        group: gettext("Fruit"),
        months: [4],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Kiwi"),
        group: gettext("Fruit"),
        months: [4, 5, 6, 7, 8, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Will Reach"),
        group: gettext("Vegetable"),
        months: [4, 5, 6, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Catalan"),
        group: gettext("Vegetable"),
        months: [4, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fennel"),
        group: gettext("Vegetable"),
        months: [5, 6, 7, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Bay Laurel"),
        group: gettext("Vegetable"),
        months: [5, 9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Sweet Potato"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Carrot"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8, 9, 10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Manioc"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Little Manioc"),
        group: gettext("Veggie"),
        months: [5, 6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Radish"),
        group: gettext("Veggie"),
        months: [5, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Quince"),
        group: gettext("Fruit"),
        months: [6],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cress"),
        group: gettext("Vegetable"),
        months: [6, 7, 8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Broccoli"),
        group: gettext("Vegetable"),
        months: [6, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pea"),
        group: gettext("Veggie"),
        months: [6, 7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Palm Heart"),
        group: gettext("Veggie"),
        months: [6, 7],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Chicory"),
        group: gettext("Vegetable"),
        months: [7, 8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Spinach"),
        group: gettext("Vegetable"),
        months: [7, 8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mustard"),
        group: gettext("Vegetable"),
        months: [7, 8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Celery"),
        group: gettext("Vegetable"),
        months: [7, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mushroom"),
        group: gettext("Veggie"),
        months: [7, 9, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cashew"),
        group: gettext("Fruit"),
        months: [8, 9, 10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lime"),
        group: gettext("Fruit"),
        months: [8, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Strawberry"),
        group: gettext("Fruit"),
        months: [8],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cauliflower"),
        group: gettext("Vegetable"),
        months: [8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Fava"),
        group: gettext("Veggie"),
        months: [8, 9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Jaboticaba"),
        group: gettext("Fruit"),
        months: [9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Medlar"),
        group: gettext("Fruit"),
        months: [9, 10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Tamarind"),
        group: gettext("Fruit"),
        months: [9],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Oregano"),
        group: gettext("Vegetable"),
        months: [9, 10, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Acerola"),
        group: gettext("Fruit"),
        months: [10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Silver Banana"),
        group: gettext("Fruit"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Mango"),
        group: gettext("Fruit"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Grape Leaf"),
        group: gettext("Vegetable"),
        months: [10, 11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Artichoke"),
        group: gettext("Veggie"),
        months: [10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Asparagus"),
        group: gettext("Veggie"),
        months: [10, 11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Khaki Tomato"),
        group: gettext("Fruit"),
        months: [10],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Melon"),
        group: gettext("Fruit"),
        months: [11, 12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Maxixe"),
        group: gettext("Veggie"),
        months: [11],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Cherry"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Damascus"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Graviola"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Lychee"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pomegranate"),
        group: gettext("Fruit"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      },
      %{  
        id: 1,
        name: gettext("Pod Noodles"),
        group: gettext("Veggie"),
        months: [12],
        image_url: "https://raw.githubusercontent.com/ronanrodrigo/Sensazonal/master/Sensazonal/System/Assets.xcassets/Content/PINEAPPLE.imageset/PINEAPPLE%403x.jpg",
      }
    ]
  end
end
